### ISSUE TITLE
Google cache doesn't use https

### ISSUE THREAD

**Issue by Peroaguaio** [dessant/view-page-archive#1]
When using other services besides Google Cache, the sites use HTTPS, but Google uses HTTP. Is that intended?

**Comment by dessant** [comment]
Yes, it's because HTTP sites would be broken because of mixed content blocking. See IMDb for example:
https://webcache.googleusercontent.com/search?q=cache:http%3A%2F%2Fwww.imdb.com%2F

An option could be added to use HTTPS whenever possible, if mixed content blocking is not a concern.

**Comment by dessant** [comment]
Search results will use HTTPS from now on, if there are any mixed content warnings with missing content, try loading the same URL with HTTP only.

Note that some search engines, like Bing, will still serve the cached page with HTTP, even if the search results use HTTPS.
