### ISSUE TITLE
Internet Archive - list all

### ISSUE THREAD

**Issue by smaragdus** [dessant/view-page-archive#11]
What I miss in **View Page Archive & Cache** is a feature available in [Resurrect Pages](https://github.com/arantius/resurrect-pages) [extension](https://addons.mozilla.org/en-US/firefox/addon/resurrect-pages/)- an option to list all [Internet Archive](https://archive.org/) records for a page, not just the latest one, screen:

![Resurrect Pages 7 0 - 2019-06-02 - 003](https://user-images.githubusercontent.com/9025757/58756270-c0ef2080-84fd-11e9-95e7-7c7a2840169a.png)

so, in stead, for example, [this single page](https://web.archive.org/web/20170509095147/http://www.softpedia.com/get/Office-tools/Text-editors/AkelPad.shtml) I will get [list of all saved pages](https://web.archive.org/web/2017*/https://www.softpedia.com/get/Office-tools/Text-editors/AkelPad.shtml).

I suppose that such an option will not be very hard to be implemented.

**Comment by smaragdus** [comment]
@dessant 

Thanks for adding an option for **Wayback Machine (all)** and **Archive.is (all)**, I appreciate it.

**Comment by wesinator** [comment]
All should be the default for archive.org 

it makes it easier to navigate history or start a new save

I also had problems loading history for some IDN (`xn--`) domains that loaded correctly from /web/*/<url> path
