### ISSUE TITLE
archive.is should be archive.fo

### ISSUE THREAD

**Issue by mkeroppi** [dessant/view-page-archive#4]
as titled.  Thanks.

**Comment by dessant** [comment]
Archive.is seems to be the primary domain, also used in the [FAQ](http://archive.fo/faq). Why should archive.fo be used instead?

**Comment by mkeroppi** [comment]
ok.  It just seems archive.fo is the main domain now where everything is redirected to, e.g., archive.is; archive.today, etc.

**Comment by dessant** [comment]
It does not redirect here http://archive.is/XrAil.
Could you share a link that redirects to archive.fo?

**Comment by dessant** [comment]
Ah yes, https://archive.today does redirect.

**Comment by dessant** [comment]
It stays on archive.is on my part. I'll ask the admin about his plans.

**Comment by dessant** [comment]
Got a quick reply, only archive.today should redirect to archive.fo, archive.is remains the primary domain.

In any case, thanks for opening the issue, I've passed along what you've observed about the archive.is redirection, it may be a bug.
