### ISSUE TITLE
Command "Archive.org" fails on URL having # part

### ISSUE THREAD

**Issue by chrisjj** [dessant/view-page-archive#7]
At archive .com, save e.g. https://www.google.com/?hello=#there <note the # part] and then open that URL and click VPA "Archive.org".

Expected: https://web.archive.org/web/20190318194110/https://www.google.com/?hello= (archived page) 
Observed: https://web.archive.org/web/https%3A%2F%2Fwww.google.com%2F%3Fhello%3D%23there "The Wayback Machine has not archived that URL."

**Comment by dessant** [comment]
@chrisjj, that's a great find! It appears other services ignore the URL hash, but we could always drop it on our end.

**Comment by dessant** [comment]
This change will need to be reverted, there are sites that use hashes to load specific content rather than navigate within the page: https://groups.google.com/forum/#!forum/dev-python

**Comment by chrisjj** [comment]
VPA's objective is finding the archives of the current URL, and this change gives success on #-abusing URLs archived at archive.org which ignores the # e.g. https://groups.google.com/forum/#!forum/dev-python -> http://web.archive.org/web/20190514193812/https://groups.google.com/forum/#!overview . It gives a fail on #-abusing URLs archived at archive.at because archive.at does not ignore the #. So it seems to me the change doesn't need reverting, but needs augmenting to make VPA #-handling specific to the archive site.

**Comment by dessant** [comment]
Yeah, we could limit it to archive.org.
