### ISSUE TITLE
Request: Keyboard shortcut for preferred archive

### ISSUE THREAD

**Issue by gloschtla** [dessant/view-page-archive#9]
Sometimes there are too many Hyperlinks to be send into archive. 
I wish, I don't need to right-click on every single Hyperlink, in order to come to the context menue. 
So there could be the option to use a keyboard shortcut, such as CTRL+Q+Click 
..in order to check for entries in the preferred internet archive in a new background tab.

**Comment by dessant** [comment]
There is no plan for adding keyboard shortcuts for clicked links, please fork the project if you need the feature.
